# for testing purposes only

version: '3.8'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "10000:6379"
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "example"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    ports:
      - "10001:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d admin" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_interval: 5s
  liquibase:
    image: liquibase/liquibase:4.25
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - './db/changelog:/liquibase/changelog'
    command: ["--defaultsFile=changelog/liquibase.properties",
              "--url=jdbc:postgresql://postgres/example",
              "--username=test",
              "--password=test",
              "update"]
